set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(ARM_NONE_EABI_ROOT "/opt/arm-gnu" CACHE PATH "GNU Arm Embedded toolchain root")
set(ARM_NONE_EABI_BIN "${ARM_NONE_EABI_ROOT}/bin")

set(CMAKE_C_COMPILER "${ARM_NONE_EABI_BIN}/arm-none-eabi-gcc" CACHE FILEPATH "C compiler")
set(CMAKE_CXX_COMPILER "${ARM_NONE_EABI_BIN}/arm-none-eabi-g++" CACHE FILEPATH "C++ compiler")
set(CMAKE_ASM_COMPILER "${ARM_NONE_EABI_BIN}/arm-none-eabi-gcc" CACHE FILEPATH "ASM compiler")

set(CMAKE_AR "${ARM_NONE_EABI_BIN}/arm-none-eabi-ar" CACHE FILEPATH "Archiver")
set(CMAKE_RANLIB "${ARM_NONE_EABI_BIN}/arm-none-eabi-ranlib" CACHE FILEPATH "Ranlib")
set(CMAKE_STRIP "${ARM_NONE_EABI_BIN}/arm-none-eabi-strip" CACHE FILEPATH "Strip")

set(ARM_NONE_EABI_OBJCOPY "${ARM_NONE_EABI_BIN}/arm-none-eabi-objcopy" CACHE FILEPATH "Objcopy")
set(ARM_NONE_EABI_SIZE "${ARM_NONE_EABI_BIN}/arm-none-eabi-size" CACHE FILEPATH "Size tool")

set(CMAKE_FIND_ROOT_PATH "${ARM_NONE_EABI_ROOT}/arm-none-eabi")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
